// Injects the matching pkmn sprite next to instance names in the
// Clever Cloud console Logs tab. Instance names are "Adjective pkmn-slug"
// (generated by CleverCloud/uuid_to_pokemon.rs), rendered inside nested open
// shadow roots of Lit components (cc-logs-app-runtime > cc-logs-instances).

(() => {
  'use strict';

  const PROCESSED = 'data-pkmn-sprite';
  const INSTANCE_HOSTS = 'cc-logs-instances-beta, cc-logs-instances';
  const observedRoots = new WeakSet();

  // Hover zoom: at scale(3) the 96x96 sprite shows at native resolution.
  // Inline styles cannot express :hover, so each shadow root hosting sprites
  // gets this stylesheet (page-level CSS does not cross shadow boundaries).
  const SPRITE_CSS = `
    .ccp-sprite {
      transform: translateY(-50%);
      transform-origin: right center;
      transition: transform 0.15s ease;
      image-rendering: pixelated;
    }
    .ccp-sprite:hover {
      transform: translateY(-50%) scale(3);
      z-index: 10;
    }
    .ccp-sprite-inline {
      transform-origin: center;
      transition: transform 0.15s ease;
      image-rendering: pixelated;
    }
    .ccp-sprite-inline:hover {
      transform: scale(3);
    }
  `;

  function ensureStyle(root) {
    if (root.querySelector('style[data-pkmn-style]')) return;
    const style = document.createElement('style');
    style.setAttribute('data-pkmn-style', '');
    style.textContent = SPRITE_CSS;
    root.append(style);
  }

  // querySelectorAll does not cross shadow boundaries: collect matches by
  // recursing into every open shadow root.
  function deepQueryAll(root, selector, out = []) {
    out.push(...root.querySelectorAll(selector));
    for (const el of root.querySelectorAll('*')) {
      if (el.shadowRoot) deepQueryAll(el.shadowRoot, selector, out);
    }
    return out;
  }

  function slugFromInstanceName(name) {
    const trimmed = name.trim().toLowerCase();
    const spaceIndex = trimmed.indexOf(' ');
    if (spaceIndex !== -1) {
      const afterAdjective = trimmed.slice(spaceIndex + 1);
      if (PKMN_NAMES.has(afterAdjective)) return afterAdjective;
    }
    const lastWord = trimmed.split(' ').pop();
    return PKMN_NAMES.has(lastWord) ? lastWord : null;
  }

  function makeSprite(slug) {
    const runtime = (globalThis.browser ?? globalThis.chrome).runtime;
    const img = document.createElement('img');
    img.src = runtime.getURL(`sprites/${slug}.png`);
    img.alt = slug;
    img.title = slug;
    return img;
  }

  // Vertically center the sprite on its instance row. The img is absolutely
  // positioned against the instance list container (the label's parent), so
  // right: 0 pins it to the panel's right edge whatever the name's width.
  function position(img) {
    const label = img.closest('label');
    if (label) img.style.top = `${label.offsetTop + label.offsetHeight / 2}px`;
  }

  function decorate(nameEl) {
    if (nameEl.hasAttribute(PROCESSED)) return;
    const slug = slugFromInstanceName(nameEl.textContent ?? '');
    if (slug === null) return;
    nameEl.setAttribute(PROCESSED, slug);
    const img = makeSprite(slug);
    const label = nameEl.closest('label');
    if (label) {
      label.parentElement.style.position = 'relative';
      img.className = 'ccp-sprite';
      img.style.cssText = [
        'position: absolute',
        'right: 0',
        'width: 32px',
        'height: 32px',
      ].join(';');
      label.prepend(img);
      position(img);
    } else {
      img.className = 'ccp-sprite-inline';
      img.style.cssText = [
        'height: 24px',
        'width: 24px',
        'vertical-align: middle',
        'margin-right: 0.25em',
      ].join(';');
      nameEl.prepend(img);
    }
  }

  function scan() {
    for (const host of deepQueryAll(document, INSTANCE_HOSTS)) {
      const root = host.shadowRoot;
      if (!root) continue;
      ensureStyle(root);
      // The instance list re-renders as instances start/stop: re-scan on
      // every mutation of this component's shadow root.
      if (!observedRoots.has(root)) {
        observedRoots.add(root);
        new MutationObserver(scan).observe(root, { childList: true, subtree: true });
      }
      for (const nameEl of root.querySelectorAll('.instance-name')) decorate(nameEl);
      // Rows move when instances come and go: refresh sprite positions.
      for (const img of root.querySelectorAll('label.instance > img')) position(img);
    }
  }

  // Test hook: under Node the internals are exported instead of auto-starting.
  if (typeof module !== 'undefined' && typeof module.exports === 'object') {
    module.exports = { deepQueryAll, slugFromInstanceName, ensureStyle, decorate, position, scan, PROCESSED };
    return;
  }

  // Periodic scan keeps up with SPA navigations (no page reload between apps)
  // and catches the logs components whenever they mount.
  scan();
  setInterval(scan, 1000);
})();
