#!/usr/bin/env python3
"""Download pkmn sprites for every instance name Clever Cloud can generate.

Sources:
- Name list: CleverCloud/uuid_to_pokemon.rs (the actual generator used by Clever Cloud)
- Sprites:   PokeAPI/sprites (CC0), default front sprite, keyed by PokeAPI pokemon id

Outputs:
- sprites/<slug>.png   (one per Clever Cloud slug, e.g. sprites/nidoran-f.png)
- pkmn-names.js     (JS Set of all slugs, loaded by the content script)
"""

import json
import re
import sys
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPRITES_DIR = ROOT / "sprites"
NAMES_JS = ROOT / "pkmn-names.js"

POKEMONS_RS_URL = "https://raw.githubusercontent.com/CleverCloud/uuid_to_pokemon.rs/master/lib/src/pokemons.rs"
POKEAPI_LIST_URL = "https://pokeapi.co/api/v2/pokemon?limit=100000"
SPRITE_URL = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/{id}.png"

# Clever Cloud slugs whose default form was renamed in PokeAPI.
ALIASES = {
    "frillish": 592,
    "jellicent": 593,
    "pyroar": 668,
    "zygarde": 718,
}


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "clever-logs-pkmn-extension"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def clever_cloud_slugs() -> list[str]:
    src = fetch(POKEMONS_RS_URL).decode()
    arrays = re.findall(r"&\[(.*?)\];", src, re.S)
    if not arrays:
        sys.exit("Could not parse POKEMONS array from pokemons.rs")
    return re.findall(r'"([^"]+)"', arrays[0])


def pokeapi_ids() -> dict[str, int]:
    data = json.loads(fetch(POKEAPI_LIST_URL))
    return {r["name"]: int(r["url"].rstrip("/").split("/")[-1]) for r in data["results"]}


def download_sprite(slug: str, poke_id: int) -> tuple[str, str | None]:
    dest = SPRITES_DIR / f"{slug}.png"
    if dest.exists() and dest.stat().st_size > 0:
        return slug, None
    try:
        data = fetch(SPRITE_URL.format(id=poke_id))
    except Exception as e:
        return slug, f"{e}"
    dest.write_bytes(data)
    return slug, None


def main() -> None:
    SPRITES_DIR.mkdir(exist_ok=True)

    slugs = clever_cloud_slugs()
    print(f"{len(slugs)} Clever Cloud pkmn slugs")

    ids = pokeapi_ids()
    mapping: dict[str, int] = {}
    unresolved = []
    for slug in slugs:
        if slug in ALIASES:
            mapping[slug] = ALIASES[slug]
        elif slug in ids:
            mapping[slug] = ids[slug]
        else:
            unresolved.append(slug)
    if unresolved:
        sys.exit(f"Unresolved slugs (add to ALIASES): {unresolved}")

    failures = []
    with ThreadPoolExecutor(max_workers=8) as pool:
        futures = [pool.submit(download_sprite, slug, pid) for slug, pid in mapping.items()]
        for i, fut in enumerate(as_completed(futures), 1):
            slug, err = fut.result()
            if err:
                failures.append((slug, err))
            if i % 100 == 0:
                print(f"  {i}/{len(futures)} sprites")

    if failures:
        for slug, err in failures:
            print(f"FAILED {slug}: {err}", file=sys.stderr)
        sys.exit(f"{len(failures)} sprite downloads failed, rerun to retry")

    empty = [p.name for p in SPRITES_DIR.glob("*.png") if p.stat().st_size == 0]
    if empty:
        sys.exit(f"Empty sprite files: {empty}")

    names_js = "// Generated by scripts/fetch_sprites.py, do not edit.\n"
    names_js += "const PKMN_NAMES = new Set(" + json.dumps(sorted(slugs)) + ");\n"
    names_js += "if (typeof module !== 'undefined') module.exports = { PKMN_NAMES };\n"
    NAMES_JS.write_text(names_js)

    print(f"OK: {len(list(SPRITES_DIR.glob('*.png')))} sprites in {SPRITES_DIR}")
    print(f"OK: {NAMES_JS}")


if __name__ == "__main__":
    main()
